<settings>
    <servers>
        <server>
            <id>http://3.1.220.10:9000/</id>
            <username>admin</username>
            <password>anu@123</password>
        </server>
    </servers>
</settings>
